# Generated by Django 4.2.4 on 2023-09-11 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='blog_image',
        ),
    ]
