# Generated by Django 4.2.4 on 2023-09-12 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Blog', '0002_remove_blog_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_image',
            field=models.ImageField(default=18, upload_to='blog_images', verbose_name='Image'),
            preserve_default=False,
        ),
    ]
