# Generated by Django 4.2.4 on 2023-09-13 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Blog', '0003_blog_blog_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ('-publish_date',)},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-comment_date',)},
        ),
        migrations.AddField(
            model_name='comment',
            name='comment',
            field=models.TextField(default=11),
            preserve_default=False,
        ),
    ]
